name: flutter_survey_js
repository: https://github.com/Goxiaoy/flutter_survey_js
packages:
  - expression/flutter_survey_js_expression
  - schema/*
  - example/
  - .

scripts:
  build:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn:
        - build_runner
  analyze:
    exec: flutter analyze --no-fatal-infos
  test:
    exec: flutter test
    packageFilters:
      dirExists:
        - test
  test_web:
    exec: flutter test --platform chrome
    packageFilters:
      scope: "flutter_survey_js_expression"
  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade --major-versions
  fix:
    exec: dart fix --apply
  build_windows:
    exec: flutter build windows --debug
    packageFilters:
      scope: "*example*"
  build_linux:
    exec: flutter build linux --debug
    packageFilters:
      scope: "*example*"
