name: Pages
on:
  workflow_run:
    workflows: ["Analyze & Test"]
    types: [completed]
    branches: [main]

  workflow_dispatch:
jobs:
  publish:
    name: Publish Github Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: "stable"
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          melos-version: "3.1.1"
      - run: |
          cd example
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
