name: Analyze & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LIBQUICKJSC_TEST_PATH: ${GITHUB_WORKSPACE}/example/build/linux/debug/bundle/lib/libquickjs_c_bridge_plugin.so

jobs:
  build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          dart pub global activate melos 3.1.1
      - name: Bootstrap melos
        run: melos bs --verbose
      - name: Setup test
        run: melos run build_linux --no-select
      - name: Run tests
        run: melos run test --no-select
      - run: |
          cd example
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true

#      - name: "Run Analyze"
#        run: melos run analyze

#      - name: "Pub Check"
#        run: |
#          melos exec -c 1 --no-private --ignore="*example*"  -- \
#            flutter pub publish --dry-run
